version: '3.8'

services:
  php:
    container_name: php-app-7.4
    build:
        context: .
        dockerfile: Dockerfile
    depends_on:
      - mysql
    volumes:
      - ./php:/var/www/html/
    ports: 
      - 8000:80

  mysql:
    container_name: mysql-app
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    container_name: adminer-app
    image: adminer
    depends_on:
      - mysql
    restart: always
    ports:
      - 3000:8080

  phpmyadmin:
    image: phpmyadmin
    restart: always
    depends_on:
      - mysql
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1